Add of statistics screen and implementation of statistics graphs
SWENT-TEAM17/OratorAI pull request #245
Opened 2024-12-11 16:49 UTC by ymarc11

This pull request introduces several significant updates and enhancements to the project, focusing on the metric graphs displayed in  a statistics screen, and associated tests. The changes include:

Key Changes:

1. StatScreen Creation:

- Created StatScreen.kt: a screen for displayhing user stats accessible from the user profile.
- Added all the necessary expressions for the navigation from and to this screen

2.  Metric Graphs:

- Implemented two metric graphs in StatScreen, one for the "talk time seconds" metric and one for the "talk time percentage" metric displaying the 10 last values of those stats.
- Added dynamic scaling to ensure graphs adapt to varying data ranges.
- Included detailed Y-axis tick labels and plotted points with enhanced color contrast.
- Displaying mean values of those two metrics beside their respective graphs.

3. Backend logic:

- Implemented a function ensureListSizeTen in the UserProfileViewModel for a correct display of stats on the graph and to overcome possible empty or under-numbered lists. (Mapped the recentData queue to the respective metric and transformed the queue to a list given as argument to this function)

4. New Tests:

- Unit Tests:
Added tests for ensureListSizeTen to verify its handling of lists with fewer, equal to, and more than 10 elements.

- UI Tests:
Added UI tests for the new stat screen insuring the elements are well displayed
Verified graph titles, graph elements, and calculated mean values in the StatisticsScreen UI.

6. Code enhancement

- Saved the maximum size of the queue (which is 10) in a variable as it was not dynamically set in the UserProfileViewModel.

Files created:
- StatScreen.kt
- StatScreenTest.kt

Files Modified:
- UserProfileViewModel.kt
- UserProfileViewModelTest.kt
- ProfileScreen.kt: Linked navigation actions for statistics graph screen.
- MainActivity.kt: Integrated GraphStats screen into the app's navigation flow.
- NavigationActions.kt
- Theme.kt: added dynamic values for graph width and height
- Color.kt: added the color for the graphs' dots

Screenshots/Previews:
<img width="256" alt="statScreen" src="https://github.com/user-attachments/assets/e00058e1-34f0-4ec7-8e88-9ce6c829928b" />

Related issues:
#168 
#244

2024-12-11 19:36 UTC, IskandarGhobril requested changes
Great work on this PR! This feature is an excellent addition that enhances the user experience by providing valuable insights into their performance through graphs. The test coverage is outstanding—98% is truly impressive!

### Key Highlights:
1. **Modular Code:**
   - The modular approach, such as the reusable line chart function, keeps the code clean, maintainable, and easy to extend.

2. **Valuable Feature:**
   - This feature adds significant value by enabling users to visualize their performance in an intuitive and effective way. It’s a great addition to the app!

### Suggestions for Improvement:
1. **Dark Mode and Color Consistency:**
   - Dark mode support is missing, and there are minor inconsistencies in the colors. Using the Material theme consistently throughout the code would address both issues. Replacing default or Android-specific colors with Material theme colors ensures a cohesive and uniform user experience across light and dark modes.

2. **Refactor EnsureListSizeTen Logic:**
   - Consider creating a new function in the `ProfileViewModel` that combines the mapping and `ensureListSizeTen` logic. Consolidating these operations in the ViewModel instead of splitting them between the ViewModel and the Stats Screen would make the code cleaner and more modular.

3. **Code Duplication:**
   - The main issue is the duplication in the `Leaderboard` top app bar. Refactoring this into a reusable component would simplify the codebase and decrease the duplication percentage.
   - Additionally, you could create a helper function to generate the column elements with line charts, reducing redundancy and enhancing modularity.

### Overall:
This is a strong PR that introduces a valuable feature to help users better understand their performance through visual graphs. Addressing the minor issues that I flagged, adding dark mode support, and eliminating code duplication will further improve its quality.

Great job, Marc—keep up the excellent work!

2024-12-12 12:49 UTC, ymarc11 commented on app/src/main/java/com/github/se/orator/ui/theme/Theme.kt
> +
Thank you.

2024-12-12 13:01 UTC, ymarc11 commented on app/src/main/java/com/github/se/orator/model/profile/UserProfileViewModel.kt
> +   * @param inputList The input list of integers to process.
Yes my bad. Thank you for noticing this mistake in the documentation.

2024-12-12 13:04 UTC, ymarc11 commented on app/src/main/java/com/github/se/orator/ui/profile/StatScreen.kt
> +              strokeWidth = 5f)
Indeed, many of the stroke widths are still hardcoded. I will add them dynamically in Theme.kt.

2024-12-12 14:12 UTC, ymarc11 commented on app/src/main/java/com/github/se/orator/ui/profile/StatScreen.kt
> +      })
Did not notice this. Thanks again.

2024-12-12 14:31 UTC, ymarc11 commented on app/src/main/java/com/github/se/orator/ui/profile/StatScreen.kt
> +                        style = AppTypography.smallTitleStyle, // Apply custom style for title
I will make it adaptable to dark mode. Thanks for the reminder.

2024-12-13 10:30 UTC, ymarc11 commented on app/src/main/java/com/github/se/orator/model/profile/UserProfileViewModel.kt
> +  }
Yes it could be done this way. I still feel my implementation is more straightforward and understandable.

2024-12-13 10:33 UTC, ymarc11 commented on app/src/main/java/com/github/se/orator/ui/profile/StatScreen.kt
> +        val tickCount = 5
You are right. Will do this.

2024-12-13 10:33 UTC, ymarc11 commented on app/src/main/java/com/github/se/orator/ui/profile/StatScreen.kt
> +              color = Color.Gray,
Fixed it.

2024-12-13 13:06 UTC, IskandarGhobril approved these changes
Thank you Marc for implementing the changes I requested. I will accept and merge it now!

2024-12-13 13:06 UTC, merged